name: spine_flutter_example
description: Demonstrates how to use the spine_flutter plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esotericsoftware_spine_flutter:
    path: ../
  cupertino_icons: ^1.0.2
  flame: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/