name: esotericsoftware_spine_flutter
description: The official Spine Flutter Runtime to load, display and interact with Spine animations.
version: 0.0.3
homepage: https://esotericsoftware.com
repository: https://github.com/esotericsoftware/spine-runtimes
issue_tracker: https://github.com/esotericsoftware/spine-runtimes/issues
documentation: https://esotericsoftware.com/spine-flutter

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  inject_js: ^2.0.0
  js: ^0.6.3
  meta: ^1.3.0
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:

  assets:
    - lib/assets/libspine_flutter.js
    - lib/assets/libspine_flutter.wasm
