name: Build and Publish Godot editor and templates

on:
  push:
    paths:
      - ".github/workflows/spine-godot.yml"
      - 'spine-godot/**'
      - 'spine-cpp/**'
  workflow_dispatch:      

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_METADATA_DISABLED: true

jobs:

  godot-editor-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps

      - name: Build Godot artifact
        shell: bash
        run: |
          mkdir -p spine-godot/godot/bin/
          touch spine-godot/godot/bin/godot.windows.opt.tools.64.exe
        # ./spine-godot/build/setup.sh 3.4.4-stable false
        # ./spine-godot/build/build.sh release_debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-editor-windows.zip
          path: spine-godot/godot/bin/godot.windows.opt.tools.64.exe

  godot-editor-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps

      - name: Build Godot artifact
        shell: bash
        run: |
          mkdir -p spine-godot/godot/bin/
          touch spine-godot/godot/bin/godot.x11.opt.tools.64
        # ./spine-godot/build/setup.sh 3.4.4-stable false
        # ./spine-godot/build/build.sh release_debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-editor-linux.zip
          path: spine-godot/godot/bin/godot.x11.opt.tools.64

  godot-editor-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps

      - name: Build Godot artifact
        shell: bash
        run: |
          mkdir -p spine-godot/godot/bin/
          mkdir -p spine-godot/godot/bin/Godot.app
          pushd spine-godot/godot/bin
          zip -r godot-editor-macos.zip Godot.app
          popd
        # ./spine-godot/build/setup.sh 3.4.4-stable false
        # ./spine-godot/build/build.sh release_debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-editor-macos.zip
          path: spine-godot/godot/bin/godot-editor-macos.zip

  godot-template-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps   

      - name: Build Godot artifact
        run: |
          mkdir -p spine-godot/godot/bin/
          touch spine-godot/godot/bin/iphone.zip
        # ./spine-godot/build/setup.sh 3.4.4-stable false
        # ./spine-godot/build/build-templates.sh ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-template-ios.zip
          path: spine-godot/godot/bin/iphone.zip

  upload-to-s3:
    needs: [godot-editor-windows, godot-editor-linux, godot-editor-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download godot-editor-windows artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-editor-windows.zip

      - name: Download godot-editor-linux artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-editor-linux.zip

      - name: Download godot-editor-macos artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-editor-macos.zip

      - name: Download godot-template-ios artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-ios.zip

      - name: Download godot-template-macos artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-macos.zip

      - name: Download godot-template-windows-release artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-windows-release.zip

      - name: Download godot-template-windows-debug artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-windows-debug.zip

     - name: Download godot-template-linux-release artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-linux-release.zip
          
      - name: Download godot-template-linux-debug artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-template-linux-debug.zip

      - name: Unpack editors and templates
        run: |            
          ls -lah

      - name: Upload artifacts to S3
        shell: bash
        if: env.AWS_ACCESS_KEY_ID != null
        run: |
          aws s3 cp godot.windows.opt.tools.64.exe s3://spine-godot/spine-godot/3.4.4-stable/
          aws s3 cp godot.x11.opt.tools.64 s3://spine-godot/spine-godot/3.4.4-stable/
          aws s3 cp godot-editor-macos.zip s3://spine-godot/spine-godot/3.4.4-stable/            
  
