name: Build and Publish Godot editor and templates

on:
  push:
    paths:
      - ".github/workflows/spine-godot.yml"
      - 'spine-godot/**'
      - 'spine-cpp/**'
  workflow_dispatch:      

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_METADATA_DISABLED: true

jobs:

  godot-windows-editor:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps

      - name: Build Godot artifact
        shell: bash
        run: |          
          ./spine-godot/build/setup.sh 3.4.4-stable false
          ./spine-godot/build/build.sh release_debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-editor-windows.zip
          path: spine-godot/godot/bin/godot.windows.opt.tools.64.exe

    upload-to-s3:
      runs-on: ubuntu-latest
      steps:
        - name: Download godot-windows-editor artifact
          uses: actions/download-artifact@v2
          with:
            name: godot-editor-windows.zip

        - name: Unpack editors and templates
          run: |
            unzip godot-editor-windows.zip
            find .
  
